# Initial configurations 
owner: nullniverse 
repo: qingniao 

sites:
 - name: TC/BFF
   url: https://bff.tradersclub.com.br
   expectedStatusCodes:
    - 500
 - name: TC/Beta
   url: https://tcbeta.tradersclub.com.br
 - name: TCCryptoBroker/MB Balances Info
   url: https://tc.tradersclub.com.br/bff/v1/crypto/broker/mb/balances-info
   expectedStatusCodes:
    - 401
   maxResponseTime: 15000
 - name: TC/Sonar
   url: https://sonar.tc.com.br
 - name: TC/Central/BM&FBovespa CVM Downloads
   url: http://seguro.bmfbovespa.com.br/rad/download/SolicitaDownload.asp
 - name: Economatica/GetStream.io
   url: https://getstream.io
 - name: CVM/RAD
   url: https://www.rad.cvm.gov.br
 - name: B3/Arquivos
   url: https://arquivos.b3.com.br
 - name: Elastic/TCSearch
   check: "tcp-ping"
   url: $ELASTIC_TCSEARCH$
   port: 9243
 - name: API/TCReportsWorker-ElevenFinancial
   url: https://api.eleven.financial
 - name: TCAPI/TCReportsWorker-TCNode/XPI
   expectedStatusCodes:
    - 403
   url: https://conteudos.xpi.com.br
 - name: TCAPI/Payment/NFE.io
   url: https://api.nfe.io
   expectedStatusCodes:
    - 404
 - name: TCAPI/TCNode/RD-Services
   url: https://api.rd.services
   expectedStatusCodes:
    - 404
 - name: TCAPI/TCAbalustreWorker/Abalustre
   url: https://api.abalustre.com
   expectedStatusCodes:
    - 403
 - name: TCAPI/Zenvia
   url: https://api.zenvia.com/
   expectedStatusCodes:
    - 404
 - name: TCAPI/StocksCrypto/CoinGecko
   check: "tcp-ping"
   url: https://api.coingecko.com/en
   port: 80
 - name: TCAPI/TCPremium/LetsEncrypt
   url: http://r3.o.lencr.org/
 - name: TCAPI/TCCrypto/SenconCRAPI
   url: https://crapi.sencon.com.br/
   expectedStatusCodes:
    - 404
 - name: TCAPI/SlackHooks
   url: https://hooks.slack.com/
   expectedStatusCodes:
    - 302
    - 200
 - name: TCAPI/TCPayment/Apple
   url: https://buy.itunes.apple.com/
 - name: Google/GoogleAPIs
   url: https://googleapis.com/
   expectedStatusCodes:
    - 404
 - name: Google/dot-com
   url: https://www.google.com
 - name: Google/com-br
   url: https://www.google.com.br
 - name: Google/Gmail-API
   url: https://gmail.googleapis.com
   expectedStatusCodes:
    - 404
 - name: Google/Gmail-API
   url: https://oauth2.googleapis.com
   expectedStatusCodes:
    - 404
 - name: Google/Gmail-API
   url: https://firestore.googleapis.com
   expectedStatusCodes:
    - 404
 - name: Google/Analytics
   url: https://analytics.google.com
   expectedStatusCode:
    - 301
 - name: Google/Elastic.io
   check: "tcp-ping"
   url: $ELASTIC_CLOUD_GCP$
   port: 443
 - name: Google/FirebaseCloudMessaging
   url: http://fcm.googleapis.com/
   expectedStatusCodes:
    - 404
 - name: Google/Accounts
   url: https://accounts.google.com
   expectedStatusCode:
    - 302
 - name: Google/PubSub
   url: http://pubsub.googleapis.com/
   expectedStatusCodes:
    - 404
 - name: AWS/TCMediaAPI-HML/S3
   url: https://tc-media-api-hml.s3.sa-east-1.amazonaws.com
   expectedStatusCodes:
    - 403
 - name: AWS/S3/SA-EAST-1
   check: "tcp-ping"
   url: https://s3-sa-east-1.amazonaws.com
   port: 443
 - name: AWS/TCReportsAPI-HML/S3
   url: https://tc-reports-api-hml.s3.sa-east-1.amazonaws.com
   expectedStatusCodes:
    - 403
 - name: AWS/TCMediaAPI/IVS
   url: https://ivs.us-east-1.amazonaws.com
   expectedStatusCodes:
    - 403
 - name: AWS/TCReportsAPI/S3
   url: https://tc-reports-api.s3.sa-east-1.amazonaws.com
   expectedStatusCodes:
    - 403
 - name: AWS/TCMatrixWallet-PRD/S3
   url: https://tc-matrix-wallet-prd.s3.sa-east-1.amazonaws.com
   expectedStatusCodes:
    - 403
 - name: AWS/TCMatrixWallet/S3
   url: https://tc-matrix-wallet.s3.sa-east-1.amazonaws.com
   expectedStatusCodes:
    - 403
 - name: AWS/TCMover/S3
   url: https://tc-mover.s3.us-east-2.amazonaws.com
   expectedStatusCodes:
    - 403
 - name: AWS/TCPremiumAPI-HML/S3
   url: https://tc-premium-api-hml.s3.sa-east-1.amazonaws.com
   expectedStatusCodes:
    - 403
 - name: AWS/TCPremiumAPI/S3
   url: https://tc-premium-api.s3.sa-east-1.amazonaws.com
   expectedStatusCodes:
    - 403
 - name: AWS/TCCompaniesAPI/S3
   url: https://tc-companies-api.s3.sa-east-1.amazonaws.com/
   expectedStatusCodes:
    - 403
 - name: Microsoft/TCNews/CognitiveAPI
   url: https://southcentralus.api.cognitive.microsoft.com/
   expectedStatusCodes:
    - 404
 - name: Microsoft/TTS
   url: https://southcentralus.tts.speech.microsoft.com/cognitiveservices/v1
   expectedStatusCodes:
    - 404
 - name: BigDataCorp/BigBoost
   url: https://bigboost.bigdatacorp.com.br/
 - name: BigDataCorp/Home
   url: https://bigdatacorp.com.br
 - name: Binance/API
   url: https://api.binance.com/
 - name: BTG/PactualDigitalHome
   url: https://www.btgpactualdigital.com
 - name: Cloudfront-service-1
   url: https://d2mi9zs24hqjjg.cloudfront.net
   expectedStatusCodes:
    - 403
 - name: Cloudfront-service-2
   url: https://d2ia36s50cbxjy.cloudfront.net
   expectedStatusCodes:
    - 403
 - name: Cloudfront-service-2
   url: https://d2kztzhteydaab.cloudfront.net
   expectedStatusCodes:
    - 403
 - name: EADBox/TCSchoolAPI
   url: https://tc.eadbox.com
   expectedStatusCodes:
    - 302
    - 200
 - name: Hubspot/API
   url: https://api.hubapi.com/
   expectedStatusCodes:
    - 302
    - 200
 - name: Hubspot/Forms
   url: https://forms.hubspot.com
   expectedStatusCodes:
    - 302
    - 200
 - name: IEX/SandboxAPI
   url: https://sandbox.iexapis.com
   expectedStatusCodes:
    - 400
 - name: IEX/CloudAPI
   url: https://cloud.iexapis.com
   expectedStatusCodes:
    - 404
 - name: Sina/W
   url: https://w.sinajs.cn/
   expectedStatusCodes:
    - 403
 - name: Sina/FinanceHome
   url: https://finance.sina.com.cn
 - name: Telegram/API
   url: https://api.telegram.org
   expectedStatusCodes:
    - 302
    - 200
 - name: TradingEconomics/API
   url: https://api.tradingeconomics.com/
 - name: Vimeo/Player
   url: https://player.vimeo.com/
   expectedStatusCodes:
    - 302
    - 200
 - name: Vindi/Sandbox
   url: https://sandbox-app.vindi.com.br
   expectedStatusCodes:
    - 302
    - 200
 - name: Vindi/Home
   url: https://vindi.com.br
 - name: Vindi/App
   url: https://app.vindi.com.br
   expectedStatusCodes:
    - 302
    - 200


status-website:
  # cname: none.org
  baseUrl: /qingniao
  logoUrl: https://github.com/nullniverse/qingniao/raw/master/birdlogo.jpeg
  name: Qingniao
  introTitle: "**Qingniao** is based on **Upptime**, the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: 'This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/nullniverse/qingniao). **Origin of the name**: The Qingniao (traditional Chinese: 青鳥; simplified Chinese: 青鸟; pinyin: qīngniǎo; "Blue (or Green) Bird (or birds)") were Blue or Green Birds which appear in Chinese mythology, popular stories, poetry, and religion. Qingniao is especially regarded as the messengers or as otherwise serving the Queen Mother of the West Xi Wangmu.'
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
